### ISSUE TITLE
[EXAMPLE] Selector not reach

### ISSUE THREAD

**Issue by azrod** [FrangipaneTeam/bean#12]
In this example selector `example_subnet` not reached

```
apiVersion: drs.flexibleengine.upbound.io/v1beta1
kind: JobMySQL
metadata:
  annotations:
    meta.upbound.io/example-id: drs/v1beta1/postgresql
  labels:
    testing.upbound.io/example-name: example_drs_job_mysql
  name: example-drs-job-mysql
spec:
  forProvider:
    description: terraform demo
    direction: up
    name: example-drs-job-mysql
    netType: eip
    sourceDb:
      - engineType: mysql
        ip: 192.168.100.10
        passwordSecretRef:
          key: example-password
          name: example-drs-job-mysql-secret
          namespace: upbound-system
        user: user
        subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: example_subnet
    destinationDb:
      - ip: 192.168.100.11
        passwordSecretRef:
          key: example-password
          name: example-drs-job-mysql-secret
          namespace: upbound-system
        subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: example_subnet
        user: user
```
